import Link from "next/link";
import { ArrowLeft, Landmark } from "lucide-react";
import { JsonLd } from "@/seo/structured-data";

export const metadata = {
  title: "Advertising Disclosure | SnapFreeTools",
  description: "Read our Advertising Disclosure. Understand how advertisements support our free tools platform and how user choices are managed.",
  robots: {
    index: true,
    follow: true
  },
  alternates: {
    canonical: "https://snapfreetools.com/advertising-disclosure"
  }
};

export default function Page() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://snapfreetools.com"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "Advertising Disclosure",
        "item": "https://snapfreetools.com/advertising-disclosure"
      }
    ]
  };

  return (
    <>
      <JsonLd schema={schema} />
      <div className="max-w-4xl mx-auto px-4 py-16 space-y-6">
        {/* Breadcrumbs */}
        <nav className="flex items-center gap-2 text-xs font-semibold text-slate-500 uppercase tracking-wider mb-6">
          <Link href="/" className="hover:text-amber-600 transition-colors">Home</Link>
          <span>/</span>
          <span className="text-slate-800">Advertising Disclosure</span>
        </nav>

        {/* Content Card */}
        <div className="bg-white p-10 rounded-3xl border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3.5 mb-8">
            <div className="w-10 h-10 rounded-xl bg-slate-50 border border-slate-100 flex items-center justify-center text-slate-500 shrink-0">
              <Landmark size={20} />
            </div>
            <div>
              <h1 className="text-3xl font-black text-slate-900 leading-tight">Advertising Disclosure</h1>
              <p className="text-xs text-slate-400 font-semibold mt-1">Last Updated: July 14, 2026</p>
            </div>
          </div>
          
          <div className="prose prose-slate max-w-none space-y-6 text-slate-650 text-sm leading-relaxed">
            <p>
              This disclosure describes how SnapFreeTools ("we," "our," or "us") manages ad-supported systems and cookie data configurations.
            </p>

            <h2 className="text-lg font-extrabold text-slate-900 pt-4">1. Free Tools Support</h2>
            <p>
              Our primary mission is to offer utility tools, calculators, and file converters to users free of charge. In order to sustain this service, pay hosting and bandwidth expenses, and continue developing new tools, we may display online advertisements on this website in the future.
            </p>

            <h2 className="text-lg font-extrabold text-slate-900 pt-4">2. Endorsements Disclaimer</h2>
            <p>
              The display of ads on our website does not represent an endorsement, sponsorship, or recommendation by SnapFreeTools of the products, brands, or services shown. We do not control the specific advertisements generated by third-party advertising algorithms.
            </p>

            <h2 className="text-lg font-extrabold text-slate-900 pt-4">3. Tracking Technologies and Ads Cookie Usage</h2>
            <p>
              Display ad partners (such as Google AdSense and third-party advertising exchanges) may use cookies, device identifiers, and similar technologies to gather traffic data on our site to show personalized advertisements. Personalized ads may depend on user location and consent. Non-personalized ads may still be shown even if personalized cookies are disabled.
            </p>

            <h2 className="text-lg font-extrabold text-slate-900 pt-4">4. Cookie Preferences and CMP Hooks</h2>
            <p>
              We respect your privacy choices. Where required by regional legislation (such as GDPR or CCPA), a Consent Management Platform (CMP) will be active. You can manage your preferences or withdraw consent for advertising cookies at any time by selecting the "Manage Cookie Preferences" link in the footer.
            </p>

            <div className="pt-8 border-t border-slate-100 mt-8 text-center sm:text-left flex flex-wrap justify-between items-center gap-4">
              <Link 
                href="/contact" 
                className="text-xs font-bold text-amber-500 hover:text-amber-600 transition-colors"
              >
                Contact support via our Contact Page &rarr;
              </Link>
              <Link 
                href="/" 
                className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-500 hover:text-amber-600 transition-colors"
              >
                <ArrowLeft size={14} /> Back to Home
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
