export const EDUCATIONAL_CONTENT = `
## What Is an Investment Calculator?

An investment calculator is a mathematical utility designed to project the future value of your money. By applying the principles of compound interest, it estimates how an initial deposit, combined with regular ongoing contributions, will grow over a specified time period at an expected rate of return.

Whether you are saving for a down payment, planning for early retirement, or building an emergency fund, visualizing the trajectory of your portfolio is the first step toward reaching your financial goals.

## How Investment Growth Is Calculated

Our calculator uses a combination of deterministic financial formulas. For standard investment growth with monthly contributions, it uses two components:

1. **Future Value of a Single Sum:** To calculate how your initial deposit grows over time.
2. **Future Value of an Annuity:** To calculate how your recurring monthly contributions grow.

These two values are summed to provide your projected gross future value. We use end-of-period compounding to ensure accurate representation of standard investment accounts.

## Compound Interest Explained

Albert Einstein supposedly called compound interest the "eighth wonder of the world." Compound growth occurs when the returns generated by your investment begin generating returns of their own.

In the early years of an investment, the growth curve is relatively flat. However, over decades, exponential compounding takes over, and the majority of your portfolio's value will consist entirely of accumulated interest rather than your out-of-pocket contributions.

## How Monthly Contributions Affect Growth

Consistency is often more powerful than initial capital. Making regular monthly contributions (often called Dollar-Cost Averaging or a Systematic Investment Plan) smooths out market volatility and continually feeds your compounding engine. 

Even a modest $100 per month can yield hundreds of thousands of dollars over a 30-to-40-year horizon. The **Investment Goal** mode of this calculator allows you to reverse-engineer exactly how much you need to contribute monthly to hit a specific target.

## Investment Growth vs Contributions

It is vital to distinguish between what you saved and what your money earned:

- **Total Contributions (Principal):** The total amount of out-of-pocket money you transferred into the account over the lifespan of the investment.
- **Estimated Growth (Profit):** The purely generated mathematical return on your invested capital.

A successful long-term investment will eventually reach a crossover point where the *Estimated Growth* far exceeds your *Total Contributions*.

## How Inflation Affects Investment Value

A million dollars today will not have the same purchasing power in 30 years. Inflation acts as a silent tax on cash and investments. 

Using our **Inflation Analysis** mode, you can calculate the "present-value equivalent" of your projected future portfolio. This adjusts your future nominal value downward by an estimated annual inflation rate, giving you a realistic picture of your future purchasing power.

## How to Use This Calculator

1. **Select a Mode:** Choose from 6 different analysis tools, including Standard Growth, Compound Interest, or Goal Planning.
2. **Enter the Details:** Input your starting balance, planned monthly deposits, and investment time horizon.
3. **Estimate the Return:** Enter an expected annual return rate (e.g., 7% to 10% for diversified index funds, 3% to 5% for bonds).
4. **Analyze the Results:** Review the dashboard, the yearly breakdown table, and the growth chart to understand your financial trajectory.

## Investment Projection Example

Imagine you start with $5,000 and invest $500 every month for 20 years at an expected 8% annual return. 

At the end of 20 years:
- **Your out-of-pocket contributions:** $125,000
- **Your estimated growth:** ~$169,000
- **Total Projected Value:** ~$294,000

In this scenario, your money earned more profit than you actually deposited!

## Assumptions and Limitations

**Important:** This calculator provides a deterministic mathematical projection based *strictly* on the numbers you enter. 

It does not predict market crashes, sequence of returns risk, platform management fees, or capital gains taxes. The stock market does not return a smooth, identical percentage every single year. Real-world returns will fluctuate. Use these projections as a baseline for planning, not as a guaranteed financial promise.
`;
