export const INVESTMENT_FAQS = [
  {
    question: "What is an investment calculator?",
    answer: "An investment calculator is a financial tool that helps you estimate how much your money will grow over time. It uses compound interest formulas to project future value based on your initial deposit, regular monthly contributions, expected return rate, and investment duration."
  },
  {
    question: "How accurate is an investment calculator?",
    answer: "Investment calculators provide mathematical estimates based strictly on the assumptions you enter. While the math is 100% accurate, real-world investments fluctuate. The calculator assumes a constant return rate, which is not guaranteed in the stock market or other volatile assets."
  },
  {
    question: "What is compound growth?",
    answer: "Compound growth (or compound interest) occurs when you earn returns not just on your initial investment, but also on the returns you've previously accumulated. Over long periods, this 'interest on interest' effect can dramatically accelerate the growth of your portfolio."
  },
  {
    question: "Can I calculate monthly investments?",
    answer: "Yes, our calculator includes a 'Monthly Contribution' mode specifically designed to model Systematic Investment Plans (SIP) or recurring monthly deposits, allowing you to see how consistent saving impacts your final goal."
  },
  {
    question: "How does the investment period affect growth?",
    answer: "Time is the most crucial factor in compound growth. The longer your money remains invested, the more powerful compounding becomes. Even small monthly contributions can grow into large sums over decades due to exponential growth."
  },
  {
    question: "How does the expected return affect the result?",
    answer: "The expected annual return dictates how fast your money compounds. A higher return rate significantly increases your future value over long periods, but usually involves taking on higher investment risk. Historically, stock markets have returned around 7-10% annually before inflation."
  },
  {
    question: "What is total investment vs total growth?",
    answer: "Total investment is the actual out-of-pocket money you deposited (your initial deposit plus all monthly contributions). Total growth is the profit or interest generated by the investment. The future value is the sum of both."
  },
  {
    question: "How does inflation affect investment returns?",
    answer: "Inflation reduces the purchasing power of your money over time. For example, $100 in 20 years will buy less than it does today. Our calculator includes an Inflation Analysis mode that adjusts your projected future value to show its estimated 'present-day' purchasing power."
  },
  {
    question: "Can I compare two investment scenarios?",
    answer: "Yes, use the 'Comparison' mode to evaluate two different strategies side-by-side. You can compare how different interest rates, higher monthly contributions, or longer time horizons impact your final outcome."
  },
  {
    question: "Can I calculate how much I need to invest monthly?",
    answer: "Yes, our 'Goal Calculator' mode works in reverse. You input your target future amount and time horizon, and it mathematically calculates the exact monthly contribution required to reach that goal."
  },
  {
    question: "Does the calculator guarantee investment returns?",
    answer: "No. All projections are estimates based solely on the numbers you input. The calculator cannot predict market crashes, sequence of returns risk, or guarantee any specific financial outcome."
  },
  {
    question: "What return rate should I enter?",
    answer: "Return rates depend on your asset allocation. Conservative investments like bonds or high-yield savings might return 3-5%, while diversified stock market index funds historically average 7-10% long-term. Always research your specific investment vehicle."
  },
  {
    question: "Can I use this calculator for retirement planning?",
    answer: "Yes, it is excellent for early-stage retirement planning to estimate future portfolio balances. However, for a comprehensive retirement plan, you should also consider tax implications, safe withdrawal rates, and inflation."
  },
  {
    question: "Does this calculator include taxes or fees?",
    answer: "No, this is a gross projection calculator. It calculates pure mathematical compound growth without deducting capital gains taxes, dividend taxes, or specific platform management fees unless you manually adjust your expected return rate downward to account for them."
  },
  {
    question: "Can I share my investment calculation?",
    answer: "Yes, you can easily share your projection results with clients, partners, or friends using the 'Share Result' button, which generates a clean summary of your estimated growth."
  }
];
