export const ALL_TOOLS = [
  // --- CALCULATORS ---
  {
    id: "gpa-calculator",
    name: "GPA Calculator",
    slug: "gpa-calculator",
    group: "Calculators",
    category: "Academic Calculators",
    description: "Calculate your college or high school semester GPA easily with our free scale calculator.",
    icon: "GraduationCap",
    featured: true,
    popular: true,
    status: "live",
    future: false
  },
  {
    id: "cgpa-calculator",
    name: "CGPA Calculator",
    slug: "cgpa-calculator",
    group: "Calculators",
    category: "Academic Calculators",
    description: "Calculate your Cumulative Grade Point Average (CGPA) across multiple semesters.",
    icon: "Calculator",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "sgpa-calculator",
    name: "SGPA Calculator",
    slug: "sgpa-calculator",
    group: "Calculators",
    category: "Academic Calculators",
    description: "Find your Semester Grade Point Average (SGPA) for individual terms.",
    icon: "Percent",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "gpa-to-percentage",
    name: "GPA to Percentage Calculator",
    slug: "gpa-to-percentage",
    group: "Calculators",
    category: "Academic Calculators",
    description: "Convert your GPA score to academic percentages instantly.",
    icon: "ArrowRightLeft",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "percentage-to-gpa",
    name: "Percentage to GPA Calculator",
    slug: "percentage-to-gpa",
    group: "Calculators",
    category: "Academic Calculators",
    description: "Translate grade percentages into the standard 4.0 scale GPA.",
    icon: "ArrowLeftRight",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "required-gpa-calculator",
    name: "Required GPA Calculator",
    slug: "required-gpa-calculator",
    group: "Calculators",
    category: "Academic Calculators",
    description: "Calculate the grades needed in future courses to reach your goal GPA.",
    icon: "Target",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "final-grade-calculator",
    name: "Final Grade Calculator",
    slug: "final-grade-calculator",
    group: "Calculators",
    category: "Academic Calculators",
    description: "Find out what score you need on your final exam to pass or get an A.",
    icon: "CheckSquare",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "merit-calculator",
    name: "Merit Calculator",
    slug: "merit-calculator",
    group: "Calculators",
    category: "Academic Calculators",
    description: "Calculate university aggregate merit percentages for admissions.",
    icon: "Award",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "scholarship-calculator",
    name: "Scholarship Calculator",
    slug: "scholarship-calculator",
    group: "Calculators",
    category: "Student & Admission Tools",
    description: "Check if your GPA matches scholarship and financial aid requirements.",
    icon: "Coins",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "attendance-calculator",
    name: "Attendance Calculator",
    slug: "attendance-calculator",
    group: "Calculators",
    category: "Student & Admission Tools",
    description: "Track and manage class attendance to meet academic requirements.",
    icon: "CalendarRange",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "grade-calculator",
    name: "Grade Calculator",
    slug: "grade-calculator",
    group: "Calculators",
    category: "Student & Admission Tools",
    description: "Compute weighted grades for assignments, quizzes, and exams.",
    icon: "ClipboardList",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "credit-hour-calculator",
    name: "Credit Hour Calculator",
    slug: "credit-hour-calculator",
    group: "Calculators",
    category: "Student & Admission Tools",
    description: "Calculate total credits earned towards graduation.",
    icon: "BookOpen",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "admission-calculator",
    name: "Admission Calculator",
    slug: "admission-calculator",
    group: "Calculators",
    category: "Student & Admission Tools",
    description: "Predict college admission chances based on GPA and test scores.",
    icon: "UserCheck",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    slug: "loan-calculator",
    group: "Calculators",
    category: "Financial Calculators",
    description: "Calculate loans interest and payments schedules.",
    icon: "Coins",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "emi-calculator",
    name: "EMI Calculator",
    slug: "emi-calculator",
    group: "Calculators",
    category: "Financial Calculators",
    description: "Calculate Equated Monthly Installments for loans.",
    icon: "LineChart",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "investment-calculator",
    name: "Investment Calculator",
    slug: "investment-calculator",
    group: "Calculators",
    category: "Financial Calculators",
    description: "Compute return on investments (ROI) over time.",
    icon: "TrendingUp",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "savings-calculator",
    name: "Savings Calculator",
    slug: "savings-calculator",
    group: "Calculators",
    category: "Financial Calculators",
    description: "Track compound growth on regular savings deposits.",
    icon: "PiggyBank",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    slug: "age-calculator",
    group: "Calculators",
    category: "Utility Calculators",
    description: "Find exact age in years, months, days, minutes.",
    icon: "Calendar",
    featured: false,
    popular: false,
    status: "live",
    future: false
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    group: "Calculators",
    category: "Utility Calculators",
    description: "Calculate percentages, percentage change, discounts, taxes, and tips.",
    icon: "Percent",
    featured: false,
    popular: true,
    status: "live",
    future: false
  },
  {
    id: "discount-calculator",
    name: "Discount Calculator",
    slug: "discount-calculator",
    group: "Calculators",
    category: "Utility Calculators",
    description: "Calculate sale prices, percentage discounts, stacked deals, and total savings instantly.",
    icon: "Tag",
    featured: false,
    popular: true,
    status: "live",
    future: false
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    slug: "bmi-calculator",
    group: "Calculators",
    category: "Health Calculators",
    description: "Calculate your Body Mass Index (BMI), find your healthy weight range, and interpret your result accurately.",
    icon: "Heart",
    featured: false,
    popular: true,
    status: "live",
    future: false
  },

  // --- PDF TOOLS ---
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    slug: "pdf-to-word",
    group: "PDF Tools",
    category: "Convert from PDF",
    description: "Convert PDFs into editable DOCX files with optional OCR support.",
    icon: "FileType",
    featured: true,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "PDF to Word Converter - Convert PDF to Word Online Free",
    seoDescription: "Convert PDF to Word online free. Convert your PDF documents into editable Microsoft Word (DOCX) files without signup, watermark, or losing formatting."
  },
  {
    id: "pdf-to-text",
    name: "PDF to Text",
    slug: "pdf-to-text",
    group: "PDF Tools",
    category: "Convert from PDF",
    description: "Extract raw plain text (.txt) from PDF files instantly in your browser without uploads.",
    icon: "FileText",
    featured: true,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "PDF to Text Converter - Extract Text from PDF Online Free",
    seoDescription: "Extract text from PDF files online free inside your browser. Convert PDF to plain text (.txt) instantly without uploads, registration, or file limits."
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    slug: "merge-pdf",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Combine multiple PDF files into one document.",
    icon: "Combine",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Merge PDF Online - Combine PDF Files Free",
    seoDescription: "Merge PDF files online free. Combine multiple PDF documents into a single PDF file quickly and securely inside your browser."
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    slug: "split-pdf",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Separate pages or extract selected pages from a PDF.",
    icon: "Scissors",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Split PDF Online Free - Separate & Extract PDF Pages",
    seoDescription: "Split PDF files online free. Separate PDF pages, extract page ranges, or split into individual single-page PDFs fast and securely inside your browser."
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    slug: "compress-pdf",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Reduce PDF file size while keeping readable quality.",
    icon: "FileDown",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Compress PDF Online - Reduce PDF File Size Free",
    seoDescription: "Compress PDF files online free. Reduce PDF document file size while maintaining optimal text and image quality."
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    slug: "word-to-pdf",
    group: "PDF Tools",
    category: "Convert to PDF",
    description: "Convert DOCX files into PDF documents directly in your browser.",
    icon: "FileCode",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Word to PDF Converter – Free & Private Online Tool | SnapFreeTools",
    seoDescription: "Convert DOCX files to PDF directly in your browser. Free, private, fast, and no file upload required."
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    slug: "jpg-to-pdf",
    group: "PDF Tools",
    category: "Convert to PDF",
    description: "Combine JPG or PNG images into a PDF file.",
    icon: "Image",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "JPG to PDF Converter - Convert Images to PDF Free",
    seoDescription: "Convert JPG, PNG, and image files to PDF online free. Combine multiple pictures into a single PDF document inside your browser."
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    slug: "pdf-to-jpg",
    group: "PDF Tools",
    category: "Convert from PDF",
    description: "Convert PDF pages into high-quality JPG images.",
    icon: "FileImage",
    featured: false,
    popular: false,
    status: "live",
    future: false,
    seoTitle: "PDF to JPG Converter - Extract PDF Pages as Images Free",
    seoDescription: "Convert PDF pages into high-quality JPG or PNG images online free. Extract photos and visuals from PDF files securely."
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    slug: "unlock-pdf",
    group: "PDF Tools",
    category: "Security & Access",
    description: "Remove PDF restrictions from files the user is authorized to edit.",
    icon: "Unlock",
    featured: false,
    popular: false,
    status: "live",
    future: false,
    seoTitle: "Unlock PDF Online - Remove Password & Restrictions Free",
    seoDescription: "Unlock PDF online free. Remove passwords, editing limits, copying restrictions, and printing permissions from authorized PDF files."
  },
  {
    id: "protect-pdf",
    name: "Protect PDF",
    slug: "protect-pdf",
    group: "PDF Tools",
    category: "Security & Access",
    description: "Add password protection to PDF documents.",
    icon: "Lock",
    featured: false,
    popular: false,
    status: "live",
    future: false,
    seoTitle: "Protect PDF Online - Add Password to PDF Free",
    seoDescription: "Protect PDF online free. Add strong password protection and restrict permissions for printing, editing, and copying secure documents."
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    slug: "rotate-pdf",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Rotate PDF pages online by 90, 180, or 270 degrees permanently.",
    icon: "RotateCw",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Rotate PDF Online Free – Rotate PDF Pages",
    seoDescription: "Rotate PDF pages online for free. Rotate all pages or individual pages by 90, 180, or 270 degrees in your browser without rasterizing or losing text quality."
  },
  {
    id: "delete-pdf-pages",
    name: "Delete PDF Pages",
    slug: "delete-pdf-pages",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Delete unwanted, blank, or confidential pages from a PDF document.",
    icon: "Trash2",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Delete PDF Pages Online Free – Remove Pages from PDF",
    seoDescription: "Delete pages from PDF online free. Select and remove unwanted pages from your PDF document instantly in your browser without rasterizing or losing text quality."
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    slug: "organize-pdf",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Visually reorder, sort, swap, and arrange PDF pages.",
    icon: "LayoutGrid",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Organize & Reorder PDF Pages Online Free",
    seoDescription: "Organize and reorder PDF pages online free. Drag and drop PDF page thumbnails to rearrange page sequence in your browser without rasterizing or losing text quality."
  },
  {
    id: "watermark-pdf",
    name: "Watermark PDF",
    slug: "watermark-pdf",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Stamp text or logo watermarks onto PDF pages.",
    icon: "Stamp",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Watermark PDF Online Free – Add Text & Logo Watermarks",
    seoDescription: "Stamp text or logo watermarks onto PDF pages online free. Custom opacity, font size, rotation, and position in your browser with zero quality loss."
  },
  {
    id: "add-page-numbers-pdf",
    name: "Add Page Numbers",
    slug: "add-page-numbers-pdf",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Add automated page numbers to your PDF document.",
    icon: "Hash",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Add Page Numbers to PDF Online Free | SnapFreeTools",
    seoDescription: "Add page numbers to PDF online free. Custom positions, Page X of Y formats, Roman numerals, cover page skipping, fonts, and colors inside your browser."
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    slug: "pdf-to-excel",
    group: "PDF Tools",
    category: "Convert from PDF",
    description: "Extract PDF tables and scanned reports into Excel spreadsheets with free OCR.",
    icon: "FileSpreadsheet",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "PDF to Excel Converter with Free OCR | SnapFreeTools",
    seoDescription: "Convert PDF to editable Excel online for free. Extract tables from selectable or scanned PDFs with free browser-based OCR. Your files stay on your device."
  },
  {
    id: "sign-pdf",
    name: "Sign PDF",
    slug: "sign-pdf",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Draw, type, or upload an e-signature to sign PDF documents.",
    icon: "PenTool",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Sign PDF Online Free – Add Your Signature to PDF | SnapFreeTools",
    seoDescription: "Sign PDF documents online for free. Draw, type, or upload your electronic signature and place it on any PDF page. 100% private in-browser processing without file uploads."
  },
  {
    id: "extract-pdf-images",
    name: "Extract PDF Images",
    slug: "extract-pdf-images",
    group: "PDF Tools",
    category: "Convert from PDF",
    description: "Extract embedded images, photos, and graphics from PDF files instantly in your browser.",
    icon: "FileImage",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Extract Images from PDF Online Free - Save PDF Pictures | SnapFreeTools",
    seoDescription: "Extract images from PDF online free inside your browser. Pull embedded photos, logos, and graphics from PDF files instantly as original JPG or PNG files without server uploads."
  },
  {
    id: "edit-pdf-metadata",
    name: "Edit PDF Metadata",
    slug: "edit-pdf-metadata",
    group: "PDF Tools",
    category: "PDF Utilities",
    description: "Edit PDF document title, author, subject, keywords, creator, and timestamps in your browser.",
    icon: "Sliders",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Edit PDF Metadata Online Free - Change PDF Properties | SnapFreeTools",
    seoDescription: "Edit PDF metadata online free inside your browser. Change PDF title, author, subject, keywords, creator and document properties instantly without server uploads."
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    slug: "pdf-to-png",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Convert from PDF",
    description: "Convert PDF pages into PNG images with configurable image quality.",
    icon: "FileImage",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "png", "convert", "image", "extract"]
  },
  {
    id: "png-to-pdf",
    name: "PNG to PDF",
    slug: "png-to-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Convert to PDF",
    description: "Convert PNG images into a single PDF document.",
    icon: "Image",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["png", "pdf", "convert", "image", "combine"]
  },
  {
    id: "pdf-to-ppt",
    name: "PDF to PowerPoint",
    slug: "pdf-to-ppt",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Convert from PDF",
    description: "Convert PDF documents into editable PowerPoint presentation files.",
    icon: "Presentation",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "ppt", "pptx", "powerpoint", "convert", "slides"]
  },
  {
    id: "ppt-to-pdf",
    name: "PowerPoint to PDF",
    slug: "ppt-to-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Convert to PDF",
    description: "Convert PowerPoint presentations into PDF documents.",
    icon: "Presentation",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["ppt", "pptx", "powerpoint", "pdf", "convert", "slides"]
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    slug: "html-to-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Convert to PDF",
    description: "Convert HTML content or web pages into PDF documents.",
    icon: "FileCode",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["html", "web", "pdf", "convert", "webpage"]
  },
  {
    id: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    slug: "pdf-to-pdfa",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Convert from PDF",
    description: "Convert PDF documents to PDF/A format for long-term document archiving.",
    icon: "Archive",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "pdfa", "archive", "convert", "standards"]
  },
  {
    id: "crop-pdf",
    name: "Crop PDF",
    slug: "crop-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Crop PDF pages by adjusting their visible page boundaries.",
    icon: "Crop",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "crop", "trim", "margins", "edit"]
  },
  {
    id: "resize-pdf",
    name: "Resize PDF Pages",
    slug: "resize-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Resize PDF pages to standard or custom page dimensions.",
    icon: "Scaling",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "resize", "scale", "dimensions", "page-size"]
  },
  {
    id: "add-text-to-pdf",
    name: "Add Text to PDF",
    slug: "add-text-to-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Add editable text blocks to PDF pages.",
    icon: "Type",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "text", "add-text", "annotate", "edit"]
  },
  {
    id: "highlight-pdf",
    name: "Highlight PDF",
    slug: "highlight-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Highlight important text and sections inside PDF documents.",
    icon: "Highlighter",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "highlight", "annotate", "mark", "text"]
  },
  {
    id: "draw-on-pdf",
    name: "Draw on PDF",
    slug: "draw-on-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Draw freehand annotations and marks directly on PDF pages.",
    icon: "Pencil",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "draw", "freehand", "sketch", "annotate"]
  },
  {
    id: "fill-pdf-forms",
    name: "Fill PDF Forms",
    slug: "fill-pdf-forms",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Edit & Annotate",
    description: "Fill interactive PDF form fields, text inputs, checkboxes, and dropdowns in your browser.",
    icon: "FormInput",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Fill PDF Forms Online Free — Complete & Edit PDF Fields",
    seoDescription: "Fill PDF forms online free inside your browser. Complete fillable PDF text fields, checkboxes, dropdowns, and radio buttons without server uploads."
  },
  {
    id: "pdf-to-grayscale",
    name: "PDF to Grayscale",
    slug: "pdf-to-grayscale",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Convert PDF pages to grayscale to reduce color usage and prepare documents for printing.",
    icon: "SunMedium",
    featured: false,
    popular: false,
    status: "live",
    future: false,
    seoTitle: "Convert PDF to Grayscale Online Free — Make PDF Black & White",
    seoDescription: "Convert color PDF pages to grayscale online free inside your browser. Turn PDF documents into black and white for eco-friendly printing and reduced toner usage.",
    tags: ["pdf", "grayscale", "black-and-white", "print", "color"]
  },
  {
    id: "extract-pdf-pages",
    name: "Extract PDF Pages",
    slug: "extract-pdf-pages",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Extract selected pages from a PDF document online for free.",
    icon: "Copy",
    featured: false,
    popular: false,
    status: "live",
    future: false,
    seoTitle: "Extract PDF Pages Online Free - Save Selected Pages | SnapFreeTools",
    seoDescription: "Extract selected pages from a PDF online for free. Select individual pages or ranges and save them as a new PDF directly in your browser with no upload or signup.",
    tags: ["pdf", "extract", "pages", "split", "select"]
  },
  {
    id: "reverse-pdf-pages",
    name: "Reverse PDF Pages",
    slug: "reverse-pdf-pages",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Reverse the page order of a PDF document.",
    icon: "ArrowUpDown",
    featured: false,
    popular: false,
    status: "live",
    future: false,
    seoTitle: "Reverse PDF Pages Online Free - Reverse PDF Order",
    seoDescription: "Reverse PDF pages online for free inside your browser. Rearrange PDF documents into reverse page order with 100% client-side privacy.",
    tags: ["pdf", "reverse", "pages", "order", "reorder"]
  },
  {
    id: "pdf-page-sorter",
    name: "PDF Page Sorter",
    slug: "pdf-page-sorter",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Manage PDFs",
    description: "Sort and rearrange PDF pages into a custom page order.",
    icon: "LayoutList",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "sort", "rearrange", "organize", "pages"]
  },
  {
    id: "redact-pdf",
    name: "Redact PDF",
    slug: "redact-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Security & Access",
    description: "Permanently remove and black out sensitive text, numbers, and confidential data in PDF documents.",
    icon: "EyeOff",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Redact PDF Online Free — Permanently Black Out PDF Text",
    seoDescription: "Redact PDF files online free inside your browser. Permanently remove and black out sensitive information, text, and data from PDF documents with 100% privacy."
  },
  {
    id: "remove-pdf-password",
    name: "PDF Password Remover",
    slug: "remove-pdf-password",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "Security & Access",
    description: "Remove password protection from PDF files when the user is authorized to modify the document.",
    icon: "Unlock",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "password", "unlock", "remove-password", "security"]
  },
  {
    id: "flatten-pdf",
    name: "Flatten PDF",
    slug: "flatten-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "PDF Utilities",
    description: "Flatten fillable PDF form fields and interactive annotations into static document content in your browser.",
    icon: "Layers",
    featured: false,
    popular: true,
    status: "live",
    future: false,
    seoTitle: "Flatten PDF Online Free — Flatten PDF Forms & Annotations",
    seoDescription: "Flatten PDF files online free inside your browser. Bake interactive PDF form fields and annotations into static document content without file uploads."
  },
  {
    id: "repair-pdf",
    name: "Repair PDF",
    slug: "repair-pdf",
    ecosystem: "utility",
    group: "PDF Tools",
    category: "PDF Utilities",
    description: "Attempt to recover and repair damaged or corrupted PDF documents.",
    icon: "Wrench",
    featured: false,
    popular: false,
    status: "coming_soon",
    future: true,
    tags: ["pdf", "repair", "recover", "fix", "corrupt"]
  },

  // --- TEXT TOOLS ---
  {
    id: "word-counter",
    name: "Word Counter",
    slug: "word-counter",
    group: "Text Tools",
    category: "Text Tools",
    description: "Count words, characters, sentences, and paragraphs in real time.",
    icon: "FileText",
    featured: true,
    popular: true,
    status: "live",
    future: false
  },
  {
    id: "case-converter",
    name: "Case Converter",
    slug: "case-converter",
    group: "Text Tools",
    category: "Text Tools",
    description: "Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, and more.",
    icon: "CaseSensitive",
    featured: true,
    popular: true,
    status: "live",
    future: false
  },

  // --- IMAGE TOOLS ---
  {
    id: "image-compressor",
    name: "Image Compressor",
    slug: "image-compressor",
    group: "Image Tools",
    category: "Image Tools",
    description: "Compress JPG, PNG, and WebP images instantly inside your browser.",
    icon: "Image",
    featured: true,
    popular: true,
    status: "live",
    future: false
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    slug: "image-resizer",
    group: "Image Tools",
    category: "Image Tools",
    description: "Resize images to custom dimensions, percentages, or social media presets.",
    icon: "Scaling",
    featured: true,
    popular: true,
    status: "live",
    future: false
  },

  // --- AI TOOLS ---
  {
    id: "ai-content-rewriter",
    name: "AI Content Rewriter",
    slug: "ai-content-rewriter",
    ecosystem: "ai",
    group: "AI Writing & Content",
    category: "AI Writing",
    subcategory: "Optimization",
    description: "Rewrite, paraphrase, and improve text clarity with advanced AI models.",
    icon: "Sparkles",
    featured: true,
    popular: true,
    status: "coming_soon",
    future: true,
    tags: ["ai", "rewrite", "paraphrase", "text", "content"]
  },
  {
    id: "ai-summarizer",
    name: "AI Text Summarizer",
    slug: "ai-summarizer",
    ecosystem: "ai",
    group: "AI Writing & Content",
    category: "AI Writing",
    subcategory: "Optimization",
    description: "Summarize long articles, essays, and reports instantly with AI.",
    icon: "FileText",
    featured: false,
    popular: true,
    status: "coming_soon",
    future: true,
    tags: ["ai", "summarizer", "summary", "text"]
  },
  {
    id: "chat-pdf-ai",
    name: "Chat PDF AI",
    slug: "chat-pdf-ai",
    ecosystem: "ai",
    group: "AI Document & PDF",
    category: "AI PDF",
    subcategory: "Chat & Extraction",
    description: "Interact with PDF documents, ask questions, and extract insights using AI.",
    icon: "Bot",
    featured: true,
    popular: true,
    status: "coming_soon",
    future: true,
    tags: ["ai", "pdf", "chat", "document", "qa"]
  }
];

// Helper selectors
export function getToolsByEcosystem(ecosystem = "utility") {
  return ALL_TOOLS.filter(
    (tool) => (tool.ecosystem || "utility") === ecosystem && tool.status === "live" && !tool.future
  );
}

export function getLiveTools() {
  return ALL_TOOLS.filter((tool) => tool.status === "live" && !tool.future);
}

