export const SAVINGS_FAQS = [
  {
    question: "What is a savings calculator?",
    answer: "A savings calculator is a financial tool that helps you estimate how much your money will grow over a specific period. It takes into account your initial deposit, regular contributions, interest rate, and compounding frequency to project your future savings balance."
  },
  {
    question: "How does a savings calculator work?",
    answer: "It uses compound interest formulas to simulate the growth of your money. By inputting your starting balance, monthly contributions, and expected annual yield, the calculator computes the total future value and breaks down how much of that balance comes from your deposits versus the interest earned."
  },
  {
    question: "How do I calculate savings growth?",
    answer: "Savings growth is calculated by applying an interest rate to your principal balance over time. When you make regular contributions, the formula calculates the future value of your initial sum plus the future value of an annuity (your regular contributions), compounding both at the given frequency."
  },
  {
    question: "How much should I save each month?",
    answer: "A common rule of thumb is the 50/30/20 rule, which suggests saving 20% of your after-tax income. However, the exact amount depends on your specific financial goals. You can use our 'Required Monthly' mode to determine exactly how much you need to save to reach a specific target."
  },
  {
    question: "How does compound interest affect savings?",
    answer: "Compound interest is when you earn interest on both your original money and the interest you've already earned. Over long periods, this causes your savings to grow exponentially, meaning the wealth-building effect accelerates the longer you leave the money invested."
  },
  {
    question: "What is the difference between simple and compound interest?",
    answer: "Simple interest is calculated only on the principal amount you originally deposited. Compound interest is calculated on the principal amount AND the accumulated interest of previous periods, resulting in significantly faster growth."
  },
  {
    question: "How much emergency savings should I have?",
    answer: "Most financial experts recommend keeping 3 to 6 months' worth of essential living expenses in a liquid emergency fund. If your income is unpredictable or you have dependents, a 9 to 12-month reserve may be safer. Use our Emergency Fund mode to estimate your ideal target."
  },
  {
    question: "How long will it take to reach my savings goal?",
    answer: "The time required depends on your starting balance, how much you contribute monthly, and your interest rate. You can use the 'Savings Goal' mode of our calculator to input your target amount and instantly see the estimated timeline."
  },
  {
    question: "How do I calculate the monthly amount needed to reach a savings goal?",
    answer: "You can use the 'Required Monthly' calculator mode. It uses reverse compound interest formulas to determine the exact monthly contribution required to hit a specific financial target within a given timeframe."
  },
  {
    question: "Does a savings calculator include compound interest?",
    answer: "Yes, a premium savings calculator automatically applies compound interest. You can typically select the compounding frequency (daily, monthly, quarterly, or annually) to match the terms of your specific savings account or investment."
  },
  {
    question: "What happens if the interest rate is 0%?",
    answer: "If the interest rate is 0%, your money will not compound. Your future balance will simply be your initial deposit plus the sum of all your regular contributions. Keep in mind that at 0% interest, inflation will slowly erode the purchasing power of your money."
  },
  {
    question: "What is the difference between contributions and interest?",
    answer: "Contributions represent the actual cash you deposit out of your own pocket. Interest is the additional money paid to you by the bank or generated by the investment yield, which helps your balance grow without extra effort from you."
  },
  {
    question: "How does compounding frequency affect my savings?",
    answer: "The more frequently interest compounds, the faster your money grows. Daily compounding yields slightly more than monthly compounding, which yields more than annual compounding, because the interest gets added to your balance sooner and starts earning its own interest."
  },
  {
    question: "Are savings calculator estimates guaranteed?",
    answer: "No, calculators provide mathematical estimates based on the inputs you provide. Real-world returns can fluctuate, especially if you are investing in the stock market rather than using a fixed-rate savings account. They are excellent planning tools but not guaranteed financial advice."
  },
  {
    question: "Can I compare two different savings strategies?",
    answer: "Yes! Use our 'Comparison' mode to evaluate two different scenarios side-by-side. You can see how increasing your monthly contribution or finding a better interest rate impacts your final wealth."
  }
];
